### ISSUE TITLE
Ability to disable for page content

### ISSUE THREAD

**Issue by jhsoby** [ofbeaton/mediawiki-realnames#14]
Hi @ofbeaton and thank you for this extension! We are going to start using it for Lokalhistoriewiki.no – we have installed it in our test wiki, and it works great. However, we have one request that I have not been able to find configuration for.

**Is your feature request related to a problem? Please describe.**
We want to disable the replacement of usernames in page content (like in discussion forums and talk pages), but enable it elsewhere (most noticeably in recent changes, history and the watch list).

**Describe the solution you'd like**
Some sort of configuration that tells the extension not to replace the usernames in these contexts.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ofbeaton** [comment]
Hi! Thank you for taking the time to write.

I don't really see the need for such a feature, the extension on purpose replaces usernames everywhere at the html level and enforces a single unified format, and you haven't provided any information on your use case (the why not the how).

As an alternative, it may be that switching to a format that displays the name AND the username (see the configuration options) would satisfy your use case, I do not know. It did for us.

That said, time constraints are such that I'm not actively maintaining this extension, though to my knowledge it still works.

I'd be willing to review a PR if you submitted a well written one.

**Comment by jhsoby** [comment]
Well, the root cause I suppose is my belief that anything in wikitext should be traceable somehow. If the wikitext says "[[User:Example|Example]]", but the display text is "Realname – Example", it should be possible to understand _why_ it says "Realname [Example]" when looking at the wikitext source. So technically, what I want is the ability to exclude replacements within <div class="mw-parser-output"> tags.

Anyways, this is not a blocker for our use, so it's more of an enhancement request than anything.

(BTW, why close the issue without a reply? I understand 100 % that you don't want to/have time to work on it, but maybe someone else comes along who would want to, but then they won't notice the issue because it is closed.)

**Comment by ofbeaton** [comment]
Ya, at the time I wrote this extension there was already an extension to do replacement in the user list (which still exists and is linked to at the bottom of the extension wikipage), and years ago I think there was even one for the recent changes page. What was missing was an extension that worked in regular pages. Hence why I wrote this one.

It also works in the renderer layer after all page html is created, and isn't too aware of what "page" it's on. That is the beauty and simplicity of it. I think you might be able to add that functionality but I'm not sure.

So you could say this extension exists specifically to replace names in rendered wikitext, no matter how those names were added (wikitext, html, etc).

So while some generic configuration to omit specific pages (which could be the pages you are interested in) might be a possible feature, I personally don't see the need.

I wrote this extension near 10 years ago and because of its simplicity it has kept working with almost no modifications despite huge changes to mediawiki software.

I've also almost never had anyone submit a patch or PR, the first PR arriving 10 years after I wrote the extension and is only a coding style guide update. 

That said if you feel like submitting a PR that is well tested and well thought out, I'd be happy to review it.

As this isn't on my radar or "plan" for the extension even if I was working on it, and because I don't duck in here very often, I'm leaving this issue closed until someone submits a PR. Nothing personal and no offense intended, just project management. Nevermind that in my experience most people who open issues never come back to answer further questions, just drive-by posting, and I don't have a bot to auto-close inactive issues.

In my experience if someone is looking something specific they won't go searching in the issues of a specific project, they'll use google which will bring them to closed issues no problem. At least that has been my personal experience.

I'm glad to hear sharing the extension which I wrote for a private wiki may help you, or at least lead you to a solution that does what you want, or part of what you want! Good luck, mediawiki is an interesting place.

**Comment by ofbeaton** [comment]
Looking at the extension documentation https://github.com/ofbeaton/mediawiki-realnames/blob/master/AdvancedConfiguration.md
you may want to experiment with starting the `$wgRealnamesNamespace` array from scratch to try to omit the main page namespace.

You may also want to experiment with `$wgRealnamesReplacements` array, specificly the `body` key.

No promises these will do what you want, I haven't tried them in a decade and the documentation I wrote leaves something to be desired.

**Comment by jhsoby** [comment]
Thank you very much for the thorough reply! No worries about the closing, I totally understand your reasoning!

I'll test the namespace approach, it might be exactly what we need (depending on whether or not that will exclude history pages). I saw it in the documentation, but wasn't sure what it would do, so I didn't think to test it out. If it doesn't work, I can try to amend the code to try to achieve what we want, but my PHP skills are severely lacking, so don't hold your breath. ;-)

Either way, thank you again for making the extension, and for the useful pointers!
