### ISSUE TITLE
Add to Packagist

### ISSUE THREAD

**Issue by JeroenDeDauw** [ofbeaton/mediawiki-realnames#17]
I see [you already have stuff on Packagist](https://packagist.org/packages/ofbeaton/), but this extension is missing. This would allow installation via Composer

**Comment by ofbeaton** [comment]
Given how hands off I am with this extension now, I'm a bit leery of adding a publishing address if I'm not planning to maintain it. All the latest releases are due to contributors submitting PRs. I've even offered the extension to several people now, but nobody seems to want to take it on.

Is there still value in me adding it to packagist, if in the near (or not) future it moves elsewhere?

**Comment by ofbeaton** [comment]
done. https://packagist.org/packages/ofbeaton/mediawiki-realnames
thank you for the suggestion. if for some reason the hook doesn't pick up that it's been configured in the next release I'll take a look at it again, but I did configure it.
