### ISSUE TITLE
Inconsistent release tag naming scheme

### ISSUE THREAD

**Issue by csarn** [ofbeaton/mediawiki-realnames#20]
Versions up to 0.8.0 have a tag that is just the version numbers, i.e. "0.8.0".
Version 0.8.1 has a tag with a "v" prepended: "v0.8.1".

That is a minor inconvenience when updating version numbers in Docker files :)

**Comment by ofbeaton** [comment]
I was all ready to push a release to fix this, but in fact only `0.7.0` and `0.8.0` did not have a leading `v`, so are the outlier. All previous releases did.

I agree inconsistent naming conventions are annoying. I'm sorry it happened, but it wasn't intentional.

I'll be leaving the leading `v` on for future releases, as I have for prior releases.

Thanks for pointing it out though, I hadn't even realized I had made the mistake on the previous releases.

I should note that I'm currently talking with a group of wiki developers looking to take over the extension, so you should hopefully see a fork popping up soon. When that happens I'll do a final release and encourage people to go follow the fork. It will hopefully be updated more often and, crucially, get tested.

I'm glad you found this extension useful!
